# Generated by Django 4.2.6 on 2025-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0002_alter_profile_saved"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
