# Generated by Django 4.2.6 on 2025-04-12 11:50

import Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0003_profile_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to=Social.models.user_directory_path
            ),
        ),
    ]
