# Generated by Django 4.2.6 on 2025-04-12 12:24

import Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0004_post_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Social.models.user_directory_path,
                verbose_name="Picture",
            ),
        ),
    ]
