# Generated by Django 4.2.6 on 2025-04-12 12:35

import Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0005_remove_post_picture_remove_post_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media",
        ),
        migrations.AddField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Social.models.user_directory_path,
                verbose_name="Picture",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=Social.models.user_directory_path
            ),
        ),
    ]
